version: "3.9"
services:
  rosys:
    network_mode: host
    restart: always

  detector:
    image: "zauberzeug/tkdnn_detection_node:latest"
    profiles: ["cams"]
    restart: always
    ports:
      - "8004:80"
    environment:
      - SERVER_BASE_URL=https://learning-loop.ai
      - ORGANIZATION=zauberzeug
      - PROJECT=drawingbot
    volumes:
      - ./detector:/data
    command: "/app/start.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]
