version: "3.9"
services:
  proxy:
    image: "robotic_proxy:${TAG-latest}"
    depends_on:
      - frontend
      - system
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx-mac.conf:/etc/nginx.conf
    build:
      context: ./proxy

  system:
    image: "robot_brain_system:${TAG-latest}"
    ports:
      - "7000:80" # fastAPI
      - "5022:5022" # ssh server
    volumes:
      - ./system:/app
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    build:
      context: ./
      dockerfile: system.dockerfile
      args:
        INSTALL_DEV: "true"
    command: /app/start.sh dev

  frontend:
    image: "robot_brain_frontend:${TAG-latest}"
    ports:
      - "4200:4200" # angular dev frontend
      - "4022:4022" # ssh server
    build:
      context: ./
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
