version: "3.9"
services:
  rosys:
    network_mode: host
    restart: always

  detector:
    image: "zauberzeug/tkdnn-detection-node:nano-r32.5.0"
    profiles: ["cams"]
    restart: always
    ports:
      - "8004:80"
    environment:
      - ORGANIZATION=zauberzeug
      - PROJECT=drawingbot
    volumes:
      - ./detector:/data
    command: "/app/start.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]
