version: "3.9"
services:
  proxy:
    network_mode: host
    restart: always

  system:
    network_mode: host
    restart: always

  frontend:
    network_mode: host
    restart: always

  detector:
    image: "zauberzeug/l4t-detection_node:nano-r32.4.4"
    ports:
      - "8004:80"
    environment:
      - SERVER_BASE_URL=https://learning-loop.ai
      - ORGANIZATION=zauberzeug
      - PROJECT=drawingbot
      - USERNAME=zauberzeug
      - PASSWORD=7GE7GSryJY5eUw96
    volumes:
      - ./data/net:/model
    command: "/app/start.sh"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]
