version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:${TAG-latest}"
    volumes:
      - ./:/rosys
      - dummy:/rosys/detector # hide original folder to not trigger uvicorn reloads through active learning
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
      - /rosys/.git # hide some unnecessary large folders...
      - /rosys/.pio
      - /rosys/controller
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    environment:
      - USE_CAMS=${USE_CAMS:-false}
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    hostname: docker
    command: /rosys/start.sh debug

volumes:
  dummy: {}
