version: "3.3"
services:
  proxy:
    image: "robotic_proxy:${TAG-latest}"
    depends_on:
      - frontend
      - system
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx.conf
    build:
      context: ./proxy

  system:
    image: "robot_brain_system:${TAG-latest}"
    ports:
      - "8000:80"
    volumes:
      - ./system:/app
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    build:
      context: ./system
      dockerfile: system.dockerfile
      args:
        INSTALL_DEV: "true"
    command: /app/start.sh

  frontend:
    image: "robot_brain_frontend:${TAG-latest}"
    depends_on:
      - system
    ports:
      - "4200:4200"
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
