version: "3.9"
services:
  proxy:
    image: "robotic_proxy:${TAG-latest}"
    depends_on:
      - frontend
      - system
    network_mode: host
    restart: always
    build:
      context: ./proxy

  system:
    image: "robot_brain_system:${TAG-latest}"
    network_mode: host
    restart: always
    volumes:
      - ./system:/app
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    build:
      context: ./
      dockerfile: system.dockerfile
      args:
        INSTALL_DEV: "true"
    command: /app/start.sh dev

  frontend:
    image: "robot_brain_frontend:${TAG-latest}"
    network_mode: host
    restart: always
    build:
      context: ./
      dockerfile: frontend.dockerfile
    volumes:
      - ./frontend:/app
