version: "3.9"
services:
  rosys:
    image: "rosys-dev:${TAG-latest}"
    volumes:
      - ./:/app
      - dummy:/app/detector # hide original folder to not trigger uvicorn reloads through active learning
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
      - /app/.git # hide some unnecessary large folders...
      - /app/.pio
      - /app/controller
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    environment:
      - USE_CAMS=${USE_CAMS:-false}
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    command: /app/start.sh debug

volumes:
  dummy: {}
