version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:${TAG-latest}"
    volumes:
      - ./:/rosys
      - ./:/app
      - ~/.ssh:/root/.ssh
      - ~/.rosys:/root/.rosys
      - ~/.gitconfig:/root/.gitconfig
      - ~/.git-credentials:/root/.git-credentials
      # hide some unnecessary large folders...
      - /rosys/.git
      - /rosys/.pio
      - /rosys/controller
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    hostname: docker
    command: /rosys/start.sh debug
