version: "3.9"
services:
  rosys:
    image: "rosys-dev:${TAG-latest}"
    volumes:
      - ./:/app
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    environment:
      - USE_CAMS=${USE_CAMS:-false}
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    command: /app/start.sh debug