version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:${TAG-latest}"
    volumes:
      - ./:/rosys
      - ./:/app
      - ~/.rosys:/root/.rosys
    privileged: true
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    build:
      context: ./
      args:
        INSTALL_DEV: "true"
    cap_add:
      - SYS_NICE # allow container to set process priorities
      - SYS_PTRACE # allow profiling with py-spy
    hostname: docker
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "100"
    command: /rosys/start.sh debug
