version: "3.9"
services:
  rosys:
    image: "zauberzeug/rosys:0.1.5"
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    devices:
      - "${ESP_SERIAL:-/dev/null}:/dev/esp"
    hostname: docker
