name: Documentation

on:
  push:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install -r mkdocs_requirements.txt
          python3 -m pip install -e .
          python3 -m pip install line-profiler
      - name: Build docs
        run: mkdocs build -v
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: site
