name: Run Tests

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.6"
      - name: install curl ssl
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev
      - name: install dependencies
        run: |
          poetry config virtualenvs.create false --local
          poetry install
      - name: test
        run: pytest
